### ISSUE TITLE
RESTful-API endpoint for getting tweets by a hashtag

### ISSUE THREAD

**Issue by Rakasha** [Rakasha/demo_anymind#1]
Implement RESTful-API  to get the list of tweets with the given hashtag.

#### Tasks
- [x] The `twitter_client` must support this feature
- [x] Implement Flask endpoint
- [x] Support optional parameters

#### Optional parameters: 
- `limit`: integer, specifies the number of tweets to retrieve, the default should be 30

#### Example:

`curl -H "Accept: application/json" -H "Content-Type: application/json" -X GET http://localhost:xxxx/hashtags/Python?limit=40`
```json
[{"account": {"fullname": "Raymond Hettinger",
              "href": "/raymondh",
              "id": 14159138},
  "date": "12:57 PM - 7 Mar 2018",
  "hashtags": ["#python"],
  "likes": 169,
  "replies": 13,
  "retweets": 27,
  "text": "Historically, bash filename pattern matching was known
           as \"globbing\".  Hence, the #python module
           called \"glob\".\n\n
           >>> print(glob.glob('*.py')\n\n
           If the function were being added today, it would probably
           be called os.path.expand_wildcards('*.py') which would be
           less arcane."},
  ...
]
```
