### ISSUE TITLE
 RESTful-API endpoint for getting tweets by user

### ISSUE THREAD

**Issue by Rakasha** [Rakasha/demo_anymind#2]
Implement RESTful-API to get user tweets. 
Get the list of tweets that the user has on his feed in JSON format. 

#### Tasks:
- [x] The `twitter_client` must support this feature
- [x] Implements Flask endpoint
- [x] Support optional parameters

#### Optional parameters: 
- `limit`: integer, specifies the number of tweets to retrieve, the default should be 30

#### Example:

`curl -H "Accept: application/json" -H "Content-Type: application/json" -X GET http://localhost:xxxx/users/twitter?limit=20`
```json
[{"account": {"fullname": "Twitter",
              "href": "/Twitter",
              "id": 783214},
  "date": "2:54 PM - 8 Mar 2018",
  "hashtags": ["#InternationalWomensDay"],
  "likes": 287,
  "replies": 17,
  "retweets": 70,
  "text": "Powerful voices. Inspiring women.\n\n#InternationalWomensDay
           https://twitter.com/i/moments/971870564246634496"},
   ...
] 
```
